name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  focal:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: ./install.sh -y
  bionic:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: ./install.sh -y
